- .github/workflows/gitleaks_github_actions.yml
Adds gitleaks secret scanning to this project.
> MAT-783 Gitleaks Scanner

- model-info-parser.iml
- src/generateTypeScript.ts
- src/generators/IGenerator.ts
- src/generators/TypeScriptGenerator.ts
- src/model/Element.ts
- src/model/ElementTypeSpecifier.ts
- src/model/ModelInfo.ts
- src/model/TypeInfo.ts
- src/model/dataTypes/ComplexDataType.ts
- src/model/dataTypes/IDataType.ts
- src/model/dataTypes/MemberVariable.ts
- src/model/dataTypes/distinctDataTypes.ts
- src/model/dataTypes/parseDataType.ts
- src/model/dataTypes/primitiveDataTypes.ts
- src/model/dataTypes/system/SystemBoolean.ts
- src/model/dataTypes/system/SystemDate.ts
- src/model/dataTypes/system/SystemDateTime.ts
- src/model/dataTypes/system/SystemDecimal.ts
- src/model/dataTypes/system/SystemInteger.ts
- src/model/dataTypes/system/SystemString.ts
- src/model/dataTypes/system/SystemTime.ts
- src/templates/typescript/classTemplate.ts
- src/templates/typescript/registerPartials.ts
- src/templates/typescript/typeAliasTemplate.ts
- tslint.json
This made some of the linting rules stricter and fixed several of the offending files along the way
> MAT-1037: Stricter linting rules

- .github/workflows/unit_test_coverage.yml
- README.md
- package.json
This is a GitHub workflow action to:
- perform a clean install of all dependencies
- lint the source code for errors
- build the code (from TypeScript -> JS)
- run tests
- upload source coverage to Codacy
> MAT-1037: GitHub workflow action to run tests and send coverage to Codacy

- .github/workflows/gitleaks_github_actions.yml
- .github/workflows/unit_test_coverage.yml
- README.md
Setting up Codecov coverage scanner to see how we like it
> MAT-1087: Codecov experiments

- package-lock.json
- package.json
Turns out versions can't be re-used. So we're up to 0.0.3 now.
> MAT-1037: Version 0.0.3

- package-lock.json
- package.json
> Version 0.0.3

- test/utils.test.ts
Just adding a little coverage so that I can try publishing to NPM again
> MAT-1037: Adding some coverage

- package.json
- src/GeneratorProgram.ts
- src/generateMongoidTypes.ts
- src/generateTypeScriptTypes.ts
- src/generators/IGenerator.ts
- src/generators/MongoidTypeGenerator.ts
- src/generators/TypeScriptGenerator.ts
Just a little cleanup/refactoring to the work @adongare did
> MAT-1049- Some tweaks to the generator scripts

- package.json
- src/generateTypeScriptTypes.ts
- src/templates/typescript/complexMemberTemplate.ts
This just makes all the fields optional in TypeScript. Leaving them as-is results in invalid TypeScript files
> Release 0.0.4

- .eslintrc.js
- src/GeneratorProgram.ts
- src/collectionUtils/BlacklistedTypesPredicate.ts
- src/collectionUtils/ExtractDataTypeTransformer.ts
- src/collectionUtils/ModifyExtensionTypeTransformer.ts
- src/collectionUtils/RemoveParentTransformer.ts
- src/collectionUtils/core/FalsePredicate.ts
- src/collectionUtils/core/NOPTransformer.ts
- src/collectionUtils/core/TruePredicate.ts
- src/generateMongoidTypes.ts
- src/generateTypeScriptTypes.ts
- src/preprocessors/BasePreprocessor.ts
- src/preprocessors/MongoidPreprocessor.ts
- src/preprocessors/MongoosePreprocessor.ts
- src/preprocessors/Preprocessor.ts
- src/preprocessors/TypeScriptPreprocessor.ts
- test/collectionUtils/testImpls/ExtractValueTransformer.ts
- test/collectionUtils/testImpls/LowerTransformer.ts
- test/collectionUtils/testImpls/UpperTransformer.ts
- test/model/dataTypes/EntityDefinitionBuilder.ts
- test/preprocessors/BasePreprocessor.test.ts
- test/preprocessors/MongoidPreprocessor.test.ts
- test/preprocessors/MongoosePreprocessor.test.ts
- test/preprocessors/TypeScriptPreprocessor.test.ts
MAT-1145: Added a preprocessor to modify the EntityCollection before the generator executes
> MAT-1145: Added Preprocessor

- src/generators/MongoidTypeGenerator.ts
Sorted certain elements to the top of the list of exported Mongoid modules. Also fixed issue with periods in type names.
> MAT-1178 models.rb sorting and periods in names

- src/generators/MongoidTypeGenerator.ts
- src/templates/helpers/templateHelpers.ts
- src/templates/rubymongoid/classTemplate.ts
- src/templates/rubymongoid/transformMemberTemplate.ts
- test/generateMongoidTypes.test.ts
- test/templates/helpers/templateHelpers.test.ts
Addressed important Ruby lints & changed import order for primitivetypes
> MAT-1179 Address ruby lints for mongoid

- src/templates/rubymongoid/classTemplate.ts
Two small changes in the Mongoid class template to address @adongare 's latest findings
> MAT-1198: fixed typo in Mongoid super class invocation, and fixed system type assignments

- src/templates/rubymongoid/classTemplate.ts
- test/generateMongoidTypes.test.ts
- Removed typeName in mongoid models as that will be added by mongoid by default
- Address lint
> Remove typeName and address lint

- src/templates/rubymongoid/complexMemberTemplate.ts
- test/generateMongoidTypes.test.ts
- referred models with their namespace
> MAT-1240 uninitialized constants issue while persisting models in bonnie

- .github/workflows/npm-publish.yml
- .github/workflows/unit_test_coverage.yml
TypeScript models should be able to parse and serialize JSON
> Release 0.0.5

- .github/CODEOWNERS
- package.json
Also adding Dan and Giff as code owners
> Upgrading version to 0.0.6

- src/templates/rubymongoid/classTemplate.ts
Bundle entry has a reference to a 'Resource' instance. This case was not handled. The previous implementation handled only resources in collections.
> MAT-1475 Better Resource type handling

- .github/dependabot.yml
Removing dependabot, as we are now relying on depfu
> Removing dependabot

- package-lock.json
- package.json
MAT-2555 version update for release v1.0.2
> update version for new release
